//! The `.xm`, `.mod` and `.vcv` parsers against the shared corpus of the Python
//! oracle: `tests/fixtures/parity/project_modules_corpus.json`, regenerated by
//! `tests/fixtures/parity/generate_project_fixtures.py`. Every case is a committed
//! fixture (or inline bytes) plus byte mutations, run under lowered limits where
//! the case says so. A verdict is either the sha256 of the snapshot's canonical
//! JSON or the exact error message (a `malformed JSON:` diagnostic is compared by
//! its class, because serde_json and Python word syntax errors differently).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::indexing_slicing)]

use std::path::{Path, PathBuf};

use apw_core::{canonical_json_utf8, sha256_hex};
use apw_daemon::project::{detect_format, snapshot_to_golden, Limits};
use serde_json::Value;

mod common;

fn projects_root() -> PathBuf {
    common::fixtures().join("projects")
}

fn corpus() -> Value {
    common::parity_json("project_modules_corpus.json")
}

fn from_hex(text: &str) -> Vec<u8> {
    apw_core::python_from_hex(text).unwrap()
}

fn case_bytes(case: &Value, bases: &Value) -> Vec<u8> {
    let mut data = if let Some(hex) = case.get("hex") {
        from_hex(hex.as_str().unwrap())
    } else if let Some(reference) = case.get("ref") {
        from_hex(bases[reference.as_str().unwrap()].as_str().unwrap())
    } else {
        std::fs::read(projects_root().join(case["base"].as_str().unwrap())).unwrap()
    };
    for mutation in case.get("mut").and_then(Value::as_array).into_iter().flatten() {
        let mutation = mutation.as_array().unwrap();
        match mutation[0].as_str().unwrap() {
            "truncate" => data.truncate(mutation[1].as_u64().unwrap() as usize),
            "set" => {
                let offset = mutation[1].as_u64().unwrap() as usize;
                let patch = from_hex(mutation[2].as_str().unwrap());
                let head = data[..offset.min(data.len())].to_vec();
                let tail = data.get(offset + patch.len()..).unwrap_or_default().to_vec();
                data = [head, patch, tail].concat();
            }
            "append" => data.extend(from_hex(mutation[1].as_str().unwrap())),
            other => panic!("unknown mutation {other}"),
        }
    }
    data
}

fn limits_for(case: &Value) -> Limits {
    let mut limits = Limits::default();
    if let Some(overrides) = case.get("limits") {
        if let Some(value) = overrides.get("max_project_file_bytes") {
            limits.max_project_file_bytes = value.as_u64().unwrap();
        }
        if let Some(value) = overrides.get("max_tar_members") {
            limits.max_tar_members = value.as_u64().unwrap() as usize;
        }
        if let Some(value) = overrides.get("max_tar_bytes") {
            limits.max_tar_bytes = value.as_u64().unwrap() as usize;
        }
    }
    limits
}

fn verdict(case: &Value, bases: &Value, directory: &Path) -> Value {
    let path = directory.join(format!("input{}", case["ext"].as_str().unwrap()));
    std::fs::write(&path, case_bytes(case, bases)).unwrap();
    let format = detect_format(&path).unwrap();
    match format.parse(&path, &limits_for(case)) {
        Ok(snapshot) => {
            let canonical = canonical_json_utf8(&snapshot_to_golden(&snapshot)).unwrap();
            serde_json::json!({ "ok": sha256_hex(&canonical) })
        }
        Err(message) => {
            let message = message.replace(&path.to_string_lossy().into_owned(), "<path>");
            let message = if message.starts_with("malformed JSON:") { "malformed JSON:".to_owned() } else { message };
            serde_json::json!({ "error": message })
        }
    }
}

#[test]
fn every_module_and_vcv_corpus_case_matches_the_oracle() {
    let document = corpus();
    let bases = &document["bases"];
    let cases = document["cases"].as_array().unwrap();
    assert!(cases.len() > 6000, "the corpus shrank to {} cases", cases.len());
    let directory = tempfile::tempdir().unwrap();
    let mut mismatches = Vec::new();
    let (mut accepted, mut refused) = (0, 0);
    for case in cases {
        let expected = &case["expect"];
        let produced = verdict(case, bases, directory.path());
        if expected.get("ok").is_some() {
            accepted += 1;
        } else {
            refused += 1;
        }
        let same = &produced == expected;
        if !same {
            mismatches.push(format!("{}: oracle {expected}, rust {produced}", case["name"].as_str().unwrap()));
        }
    }
    assert!(accepted > 1000 && refused > 1000, "{accepted} accepted, {refused} refused");
    assert!(mismatches.is_empty(), "{} of {} cases differ:\n{}", mismatches.len(), cases.len(), mismatches.iter().take(40).cloned().collect::<Vec<_>>().join("\n"));
}

#[test]
fn the_corpus_keeps_limit_minus_one_limit_and_limit_plus_one_for_every_cap() {
    let document = corpus();
    let cases = document["cases"].as_array().unwrap();
    let accepted = |name: &str| -> bool {
        let case = cases.iter().find(|case| case["name"] == name).unwrap_or_else(|| panic!("corpus lost {name}"));
        case["expect"].get("ok").is_some()
    };
    for (name, expected) in [
        ("xm_channels_0", false), ("xm_channels_1", true), ("xm_channels_32", true), ("xm_channels_33", false),
        ("xm_patterns_255", true), ("xm_patterns_256", true), ("xm_patterns_257", false),
        ("xm_instruments_254", true), ("xm_instruments_255", true), ("xm_instruments_256", false),
        ("xm_samples_per_instrument_95", true), ("xm_samples_per_instrument_96", true), ("xm_samples_per_instrument_97", false),
        ("xm_rows_0", false), ("xm_rows_1", true), ("xm_rows_256", true), ("xm_rows_257", false),
        ("xm_order_count_256", true), ("xm_order_count_257", true),
        ("cap_tar_bytes_minus_1", false), ("cap_tar_bytes_exact", true), ("cap_tar_bytes_plus_1", true),
        ("cap_tar_bytes_sized_minus_1", false), ("cap_tar_bytes_sized_exact", true),
        ("cap_members_2_of_3", true), ("cap_members_3_of_3", true), ("cap_members_4_of_3", false),
        ("cap_file_size_-1", false), ("cap_file_size_+0", true), ("cap_file_size_+1", true),
        ("json_depth_total_127", true), ("json_depth_total_128", true), ("json_depth_total_129", false),
        ("json_int_4300_digits", true), ("json_int_4301_digits", false),
        ("zstd_window_2_27", true), ("zstd_window_2_27_plus", false),
    ] {
        assert_eq!(accepted(name), expected, "{name}");
    }
}
