[package]
name = "apw-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
warnings = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"

[dependencies]
apw-core.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
