//! Interop against artifacts the audio-provenance POC produced.
//!
//! FIXTURE PROVENANCE: `poc_*.json` are unmodified manifests from the POC's own founder evidence
//! package, and `sample.c2pa` / `sample_signed.wav` were written by `daemon/c2pa_engine`'s signer
//! through the POC's venv. Nothing here was generated by the code under test.

#![allow(clippy::unwrap_used, clippy::panic)]

use audio_provenance_core::{CodedError, ProofLevel, SigningKey, VerificationStatus};
use audio_provenance_manifest::{
    BindingOutcome, C2paClaimStatus, C2paStore, HardBinding, ManifestDraft, ManifestSchema,
    MarkBinding, SignerIdentityBinding, UnverifiedManifest, validate_apw_invariants,
};
use serde_json::Value;

const SIGNED: &[u8] = include_bytes!("fixtures/poc_signed_manifest.json");
const UNOBSERVED: &[u8] = include_bytes!("fixtures/poc_unobserved_manifest.json");
const SIGNED_WAV: &[u8] = include_bytes!("fixtures/sample_signed.wav");
const SIDECAR: &[u8] = include_bytes!("fixtures/sample.c2pa");
const AIFF: &[u8] = include_bytes!("fixtures/sample.aiff");

fn admit_signed() -> audio_provenance_manifest::Manifest {
    let mut value: Value = serde_json::from_slice(SIGNED).unwrap();
    // Preserve the historical fixture byte-for-byte on disk, but update its synthetic admission
    // copy to the current complete-coverage contract and genuinely re-sign that copy.
    value["observation_coverage"]["counters"]["bypassed_buffers"] = Value::from(0u8);
    let signed = resign(&value);
    UnverifiedManifest::parse(&signed)
        .unwrap()
        .admit(ManifestSchema::ApwV0)
        .unwrap_or_else(|failure| panic!("{}: {}", failure.error.code(), failure.error))
}

#[test]
fn a_real_poc_manifest_admits_and_reports_only_key_possession() {
    let manifest = admit_signed();

    assert_eq!(manifest.schema(), ManifestSchema::ApwV0);
    // The invariant the whole product rests on: a cryptographically perfect self-generated
    // signature yields no identity at all.
    assert!(manifest.signer().identity().is_none());
    assert_eq!(
        manifest.signer().proof_level(),
        ProofLevel::UnknownUnobserved
    );
    assert_eq!(
        manifest.signer().signer_id(),
        Some(manifest.signature().signer_id.as_str())
    );
    assert_eq!(manifest.signed_at(), Some("2026-08-31"));

    let export_digest = manifest.value()["export"]["sha256"].as_str().unwrap();
    assert_eq!(
        manifest.evaluate_hard_binding(export_digest),
        BindingOutcome::Match
    );
    assert_eq!(
        manifest.evaluate_hard_binding(&"0".repeat(64)),
        BindingOutcome::Mismatch
    );

    let coverage = manifest.observation_coverage().unwrap();
    assert_eq!(
        coverage.status(),
        audio_provenance_core::CoverageStatus::CompleteObservedPath
    );
    assert_eq!(coverage.proof_level(), ProofLevel::Inferred);

    let association = manifest.association().unwrap();
    assert_eq!(
        association.status(),
        audio_provenance_core::AssociationStatus::InferredMatch
    );
    assert_eq!(association.proof_level(), ProofLevel::Inferred);

    let claim = manifest.c2pa_claim().unwrap();
    assert_eq!(claim.status(), C2paClaimStatus::Embedded);
    assert_eq!(
        claim.verification_status(),
        Some(VerificationStatus::Verified)
    );
    assert!(claim.binding_covers_export());

    assert!(
        manifest
            .findings()
            .iter()
            .all(|f| f.severity() != audio_provenance_manifest::Severity::Error)
    );
}

#[test]
fn the_legacy_complete_claim_without_bypass_telemetry_is_refused() {
    let failure = UnverifiedManifest::parse(SIGNED)
        .unwrap()
        .admit(ManifestSchema::ApwV0)
        .unwrap_err();
    assert_eq!(failure.error.code(), "manifest_invariants_failed");
    assert!(
        failure
            .findings
            .iter()
            .any(|finding| finding.code() == "coverage_counter_missing"
                && finding.path().ends_with("bypassed_buffers")),
        "{:?}",
        failure.findings
    );
}

#[test]
fn the_honest_null_manifest_admits_and_claims_nothing() {
    let manifest = UnverifiedManifest::parse(UNOBSERVED)
        .unwrap()
        .admit(ManifestSchema::ApwV0)
        .unwrap_or_else(|failure| panic!("{}", failure.error));

    assert_eq!(
        manifest.association().unwrap().status(),
        audio_provenance_core::AssociationStatus::Unavailable
    );
    assert_eq!(
        manifest.observation_coverage().unwrap().status(),
        audio_provenance_core::CoverageStatus::UnknownCoverage
    );
}

#[test]
fn a_moved_byte_under_a_valid_signature_fails_admission_not_validation() {
    let mut value: Value = serde_json::from_slice(SIGNED).unwrap();
    value["session_id"] = Value::String("someone-elses-session".into());
    let bytes = serde_json::to_vec(&value).unwrap();

    let failure = UnverifiedManifest::parse(&bytes)
        .unwrap()
        .admit(ManifestSchema::ApwV0)
        .unwrap_err();
    assert_eq!(failure.error.code(), "signature_content_hash_mismatch");
    // The rejected candidate survives so a recovery ladder can record it rather than losing it.
    assert_eq!(failure.manifest.bytes(), bytes.as_slice());
}

/// The gate that matters: a signature can be perfectly valid over a manifest that lies. Admission
/// runs the ported invariants AFTER the signature and refuses anyway.
#[test]
fn a_validly_signed_manifest_that_overstates_its_association_is_refused() {
    let mut value: Value = serde_json::from_slice(SIGNED).unwrap();
    value["stem_export_association"]["apw:proof_level"] = Value::String("directly_observed".into());
    let bytes = resign(&value);

    let failure = UnverifiedManifest::parse(&bytes)
        .unwrap()
        .admit(ManifestSchema::ApwV0)
        .unwrap_err();
    assert_eq!(failure.error.code(), "manifest_invariants_failed");
    assert!(
        failure
            .findings
            .iter()
            .any(|f| f.code() == "association_proof_level_overstated"),
        "{:?}",
        failure.findings
    );
}

#[test]
fn a_signed_c2pa_claim_may_not_declare_an_externally_verified_signer() {
    let mut value: Value = serde_json::from_slice(SIGNED).unwrap();
    value["c2pa_claim"]["signer"]["apw:proof_level"] = Value::String("externally_verified".into());
    let findings = validate_apw_invariants(&value);
    assert!(
        findings
            .iter()
            .any(|f| f.code() == "c2pa_claim_signer_identity_overstated"),
        "{findings:?}"
    );
}

#[test]
fn an_integer_wider_than_the_signable_range_is_refused_at_parse() {
    let bytes = br#"{"schema":"audio-provenance-manifest-v0","n":18446744073709551616}"#;
    let error = UnverifiedManifest::parse(bytes).unwrap_err();
    assert_eq!(error.code(), "canonical_json_integer_out_of_range");
}

#[test]
fn a_audio_provenance_record_round_trips_through_the_draft_and_back() {
    let key = SigningKey::from_raw_bytes(&[7u8; 32]).unwrap();
    let draft = ManifestDraft::new(
        "2026-08-31",
        HardBinding::new(&"ab".repeat(32), Some(352_300), None).unwrap(),
    )
    .unwrap()
    .with_locator_salt(audio_provenance_core::LocatorSalt::from_bytes([2u8; 16]))
    .with_mark(MarkBinding {
        version: 0,
        namespace: 0,
    });

    let signature = key
        .sign_manifest(&draft.to_unsigned_value().unwrap(), "demo.key")
        .unwrap();
    let sealed = draft.seal(&signature).unwrap();

    let manifest = UnverifiedManifest::parse(&sealed)
        .unwrap()
        .admit(ManifestSchema::AudioProvenanceV1)
        .unwrap_or_else(|failure| panic!("{}", failure.error));

    assert_eq!(manifest.bytes(), sealed.as_slice());
    assert_eq!(
        manifest.evaluate_hard_binding(&"ab".repeat(32)),
        BindingOutcome::Match
    );
    // The locator is derived from the signer's public key and the record's own signed salt, so it
    // exists before the audio is marked and still cannot be re-pointed after signing.
    let expected = audio_provenance_core::derive_locator(
        &key.public_key_bytes(),
        &audio_provenance_core::LocatorSalt::from_bytes([2u8; 16]),
    );
    assert_eq!(manifest.mark_locator(), Some(expected));
    assert_eq!(
        manifest.locator_salt(),
        Some(audio_provenance_core::LocatorSalt::from_bytes([2u8; 16]))
    );
    assert!(manifest.key_possession().is_ok());

    // A pretty-printed copy of the same record carries the same signature and is still refused,
    // because the registry's record id is derived from bytes and those bytes moved.
    let pretty = serde_json::to_vec_pretty(manifest.value()).unwrap();
    let failure = UnverifiedManifest::parse(&pretty)
        .unwrap()
        .admit(ManifestSchema::AudioProvenanceV1)
        .unwrap_err();
    assert_eq!(failure.error.code(), "noncanonical_manifest");
}

#[test]
fn admitting_under_the_wrong_family_is_refused_before_anything_else() {
    let failure = UnverifiedManifest::parse(SIGNED)
        .unwrap()
        .admit(ManifestSchema::AudioProvenanceV1)
        .unwrap_err();
    assert_eq!(failure.error.code(), "manifest_schema_mismatch");
}

#[test]
fn an_embedded_c2pa_hard_binding_recomputes_over_the_asset_it_covers() {
    let store = C2paStore::from_wav(SIGNED_WAV).unwrap();
    assert!(matches!(
        store.location(),
        audio_provenance_manifest::StoreLocation::EmbeddedWavChunk { .. }
    ));
    let labels = store.labels().unwrap();
    assert!(labels.iter().any(|l| l == "c2pa.hash.data"), "{labels:?}");
    assert!(labels.iter().any(|l| l == "c2pa.claim.v2"), "{labels:?}");

    let binding = store.hard_binding().unwrap();
    assert_eq!(binding.evaluate(SIGNED_WAV).unwrap(), BindingOutcome::Match);

    // One flipped audio byte outside the excluded manifest chunk breaks it.
    let mut altered = SIGNED_WAV.to_vec();
    altered[600] ^= 0x01;
    assert_eq!(
        binding.evaluate(&altered).unwrap(),
        BindingOutcome::Mismatch
    );
}

#[test]
fn a_bare_sidecar_store_binds_the_aiff_beside_it() {
    let store = C2paStore::from_sidecar(SIDECAR).unwrap();
    assert_eq!(
        store.location(),
        audio_provenance_manifest::StoreLocation::Sidecar
    );
    let binding = store.hard_binding().unwrap();
    // The sidecar binding excludes nothing, so it covers every byte of the asset.
    assert!(binding.exclusions().is_empty());
    assert_eq!(binding.evaluate(AIFF).unwrap(), BindingOutcome::Match);
    assert_eq!(
        audio_provenance_manifest::sidecar_path_for("/x/sample.aiff"),
        "/x/sample.c2pa"
    );
}

#[test]
fn a_wav_without_provenance_reports_absence_rather_than_failure() {
    let plain = &SIGNED_WAV[..1044];
    let mut wav = plain.to_vec();
    let size = u32::try_from(wav.len() - 8).unwrap();
    wav[4..8].copy_from_slice(&size.to_le_bytes());
    assert_eq!(
        C2paStore::from_wav(&wav).unwrap_err().code(),
        "c2pa_store_absent"
    );
}

#[test]
fn an_external_identity_is_the_only_shape_that_carries_a_name() {
    let resolved = SignerIdentityBinding::externally_verified("Signal Room Studios", "demo-anchor");
    assert_eq!(resolved.identity(), Some("Signal Room Studios"));
    assert_eq!(resolved.proof_level(), ProofLevel::ExternallyVerified);
    assert!(resolved.signer_id().is_none());
}

/// Re-signs a mutated manifest with a fresh key so the signature is genuinely valid over it.
fn resign(value: &Value) -> Vec<u8> {
    let key = SigningKey::from_raw_bytes(&[3u8; 32]).unwrap();
    let unsigned = audio_provenance_core::unsigned_manifest_view(value);
    let signature = key.sign_manifest(&unsigned, "demo.key").unwrap();
    let mut signed = unsigned;
    signed["portable_signature"] = serde_json::to_value(&signature).unwrap();
    serde_json::to_vec(&signed).unwrap()
}

/// A malformed `locator_salt` is a MANIFEST verdict, not a registry outage.
///
/// The registry refuses such a record too, but a registry-layer refusal reaches a verifier as
/// `Unavailable(IndexCorrupt)`, which reads as "the registry was down" for a record that is simply
/// invalid. The invariant port is what makes it `manifest_invariants_failed` instead.
#[test]
fn a_malformed_locator_salt_fails_admission_rather_than_reading_as_an_outage() {
    let key = SigningKey::from_raw_bytes(&[7u8; 32]).unwrap();
    let draft = ManifestDraft::new(
        "2026-08-31",
        HardBinding::new(&"ab".repeat(32), Some(352_300), None).unwrap(),
    )
    .unwrap()
    .with_locator_salt(audio_provenance_core::LocatorSalt::from_bytes([2u8; 16]));

    let mut unsigned = draft.to_unsigned_value().unwrap();
    unsigned["locator_salt"] = Value::String("zz".repeat(16));
    let signature = key.sign_manifest(&unsigned, "demo.key").unwrap();
    let mut value = unsigned;
    value["portable_signature"] = serde_json::to_value(&signature).unwrap();
    let sealed = audio_provenance_core::canonical_json(&value).unwrap();

    let failure = UnverifiedManifest::parse(&sealed)
        .unwrap()
        .admit(ManifestSchema::AudioProvenanceV1)
        .unwrap_err();
    assert_eq!(failure.error.code(), "manifest_invariants_failed");
    assert!(
        failure
            .findings
            .iter()
            .any(|finding| finding.code() == "locator_salt_malformed"),
        "{:?}",
        failure.findings
    );
}
