use std::path::PathBuf;

use clap::{Parser, Subcommand};

/// The default RFC 3161 endpoint `daemon/time_anchor/anchor.py` uses when
/// `--time-anchor` is passed with no value.
pub const DEFAULT_TSA_URL: &str = "http://timestamp.digicert.com";

pub const DEFAULT_UDP_PORT: u16 = 9876;
pub const DEFAULT_EVIDENCE_DIR: &str = "evidence";
pub const DEFAULT_MANIFEST_DIR: &str = "manifests";
pub const DEFAULT_SAMPLE_DIR: &str = "~/Music/ProvenanceSamples";
pub const DEFAULT_SIGNING_KEY: &str = "~/.apw/demo_signing_key.bin";
pub const DEFAULT_PRIVATE_KEY: &str = "~/.apw/demo_ed25519_private.key";
pub const DEFAULT_PUBLIC_KEY: &str = "~/.apw/demo_ed25519_public.key";
pub const DEFAULT_PROVENANCE_STORE: &str = "~/.apw/provenance";

#[derive(Debug, Parser)]
#[command(
    name = "apw",
    version,
    about = "Audio provenance wrapper: observe a routed stem, seal a detected export, \
             and verify what a file actually carries.",
    long_about = "Every field this binary writes carries a proof level, and a missing mark \
                  is never evidence of synthetic origin. A locally issued signing chain \
                  proves possession of a key; it is not a verified identity."
)]
pub struct Cli {
    /// Log level: error, warn, info, debug, trace.
    #[arg(long, global = true, default_value = "info")]
    pub log_level: String,

    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Receive plug-in evidence, watch for exports, and seal each one.
    Daemon(DaemonArgs),
    /// Sign one audio file into a C2PA claim and read the claim back.
    Sign(SignArgs),
    /// Report which of the four provenance states a file is in.
    Verify(VerifyArgs),
    /// Assemble, sign and write the provenance manifest for one export.
    Manifest(ManifestArgs),
}

/// Flag spellings are the ones `daemon/__main__.py::parse_args` accepts, so the
/// demo scripts' argument vectors carry over unchanged.
#[derive(Debug, clap::Args)]
pub struct DaemonArgs {
    /// UDP port for plugin events.
    #[arg(long, default_value_t = DEFAULT_UDP_PORT)]
    pub port: u16,

    /// Evidence output directory.
    #[arg(long, default_value = DEFAULT_EVIDENCE_DIR)]
    pub evidence_dir: PathBuf,

    /// Sample watch directory.
    #[arg(long, default_value = DEFAULT_SAMPLE_DIR)]
    pub sample_dir: PathBuf,

    /// Ableton .als project file to watch.
    #[arg(long)]
    pub project: Option<PathBuf>,

    /// Export directory to watch for WAV/AIFF.
    #[arg(long)]
    pub export_dir: Option<PathBuf>,

    /// Manifest output directory.
    #[arg(long, default_value = DEFAULT_MANIFEST_DIR)]
    pub manifest_dir: PathBuf,

    /// Optional local capture-session identifier. A unique value is generated by default.
    #[arg(long)]
    pub session_id: Option<String>,

    /// Identifier for the single routed stem.
    #[arg(long, default_value = "stem-1")]
    pub stem_id: String,

    /// Anchor each export hash at an RFC 3161 TSA (default server if no URL given).
    #[arg(long, num_args = 0..=1, default_missing_value = DEFAULT_TSA_URL, value_name = "TSA_URL")]
    pub time_anchor: Option<String>,

    /// Producer-declared source category. Defaults to unknown.
    #[arg(long, default_value = "unknown")]
    pub source_category: String,

    /// Local software integrity-key path. This is not hardware attestation.
    #[arg(long, default_value = DEFAULT_SIGNING_KEY)]
    pub signing_key: PathBuf,

    /// Ed25519 private key for demo integrity signing.
    #[arg(long, default_value = DEFAULT_PRIVATE_KEY)]
    pub portable_private_key: PathBuf,

    /// Portable Ed25519 public key written for independent verification.
    #[arg(long, default_value = DEFAULT_PUBLIC_KEY)]
    pub portable_public_key: PathBuf,

    /// Local provenance key-custody store used to sign the C2PA claim. The chain
    /// issued here is self-asserted, not an externally verified identity.
    #[arg(long, default_value = DEFAULT_PROVENANCE_STORE)]
    pub provenance_store: PathBuf,

    /// Provenance provider to use: local (default) or remote.
    #[arg(long)]
    pub provenance_provider: Option<String>,

    /// Generate only the JSON manifest, without the derived HTML fight card.
    #[arg(long)]
    pub no_html_report: bool,

    /// Open each generated fight card with the macOS default browser.
    #[arg(long)]
    pub open_artifacts: bool,
}

#[derive(Debug, clap::Args)]
pub struct SignArgs {
    /// Audio file to sign. Its bytes decide the container; the extension does not.
    pub asset: PathBuf,

    /// Destination for the signed copy. The source file is never rewritten.
    #[arg(long)]
    pub out: Option<PathBuf>,

    /// Destination for the detached manifest when the container cannot embed one.
    #[arg(long)]
    pub sidecar: Option<PathBuf>,

    /// Manifest title. Defaults to the asset's file name.
    #[arg(long)]
    pub title: Option<String>,

    /// Local provenance key-custody store that issues the signing material.
    #[arg(long, default_value = DEFAULT_PROVENANCE_STORE)]
    pub provenance_store: PathBuf,

    /// Provenance provider to use: local (default) or remote.
    #[arg(long)]
    pub provenance_provider: Option<String>,

    /// Print the full record as JSON instead of a summary.
    #[arg(long)]
    pub json: bool,
}

#[derive(Debug, clap::Args)]
pub struct VerifyArgs {
    /// File to verify.
    pub target: PathBuf,

    /// PEM file of trust anchors. Without one, no chain can reach `verified`.
    #[arg(long, value_name = "PEM")]
    pub trust_anchor: Option<PathBuf>,

    /// Trust the local store's own root. It proves key possession on this
    /// machine, never a verified identity.
    #[arg(long)]
    pub trust_local_root: bool,

    /// Local provenance store whose root `--trust-local-root` reads.
    #[arg(long, default_value = DEFAULT_PROVENANCE_STORE)]
    pub provenance_store: PathBuf,

    /// Detached .c2pa manifest to verify the asset against.
    #[arg(long)]
    pub sidecar: Option<PathBuf>,

    /// Print the full record as JSON instead of a summary.
    #[arg(long)]
    pub json: bool,
}

#[derive(Debug, clap::Args)]
pub struct ManifestArgs {
    /// Export to seal.
    pub export: PathBuf,

    /// Manifest output directory.
    #[arg(long, default_value = DEFAULT_MANIFEST_DIR)]
    pub manifest_dir: PathBuf,

    /// Evidence directory read for the hash chain and the evidence binding.
    #[arg(long, default_value = DEFAULT_EVIDENCE_DIR)]
    pub evidence_dir: PathBuf,

    /// Local capture-session identifier. A unique value is generated by default.
    #[arg(long)]
    pub session_id: Option<String>,

    /// Identifier for the single routed stem.
    #[arg(long, default_value = "stem-1")]
    pub stem_id: String,

    /// Producer-declared source category. Defaults to unknown.
    #[arg(long, default_value = "unknown")]
    pub source_category: String,

    /// Local software integrity-key path. This is not hardware attestation.
    #[arg(long, default_value = DEFAULT_SIGNING_KEY)]
    pub signing_key: PathBuf,

    /// Ed25519 private key for demo integrity signing.
    #[arg(long, default_value = DEFAULT_PRIVATE_KEY)]
    pub portable_private_key: PathBuf,

    /// Portable Ed25519 public key written for independent verification.
    #[arg(long, default_value = DEFAULT_PUBLIC_KEY)]
    pub portable_public_key: PathBuf,

    /// Local provenance key-custody store used to sign the C2PA claim.
    #[arg(long, default_value = DEFAULT_PROVENANCE_STORE)]
    pub provenance_store: PathBuf,

    /// Provenance provider to use: local (default) or remote.
    #[arg(long)]
    pub provenance_provider: Option<String>,

    /// Generate only the JSON manifest, without the derived HTML fight card.
    #[arg(long)]
    pub no_html_report: bool,

    /// Also write the manifest to stdout.
    #[arg(long)]
    pub stdout: bool,
}
